#!/usr/bin/env bash

export DEVSPECS_RELATIVE_DIR="${DEVSPECS_RELATIVE_DIR:-.devspecs}"
export DEVSPECS_SPECS_RELATIVE_DIR="${DEVSPECS_SPECS_RELATIVE_DIR:-${DEVSPECS_RELATIVE_DIR}/specs}"
export DEVSPECS_MEMORY_RELATIVE_DIR="${DEVSPECS_MEMORY_RELATIVE_DIR:-${DEVSPECS_RELATIVE_DIR}/memory}"
export DEVSPECS_PROMPTS_RELATIVE_DIR="${DEVSPECS_PROMPTS_RELATIVE_DIR:-${DEVSPECS_RELATIVE_DIR}/prompts}"
export DEVSPECS_TEMPLATES_RELATIVE_DIR="${DEVSPECS_TEMPLATES_RELATIVE_DIR:-${DEVSPECS_RELATIVE_DIR}/templates}"
export DEVSPECS_CONTRACTS_NESTED_RELATIVE_DIR="${DEVSPECS_CONTRACTS_NESTED_RELATIVE_DIR:-contracts}"

export DEVSPECS_PLAN_TEMPLATE_RELATIVE_FILE_NAME="${DEVSPECS_TEMPLATES_RELATIVE_DIR}/plan.template.md"
